__version__ = "0.5.1"

from .common import (
    DOCX_MIME,
    MD_MIME,
    PDF_MIME,
    TXT_MIME,
    DocumentBytes,
    DocumentError,
    DocumentKind,
)
from .detection import DetectedDocumentType, detect_document_type
from .docx import (
    AddressableComment,
    AddressableSpan,
    DocxDocument,
    InlineSegment,
    InlineSegmentKind,
    SegmentReplacement,
    SpanRole,
    TextSegment,
    UnsupportedRevisionError,
    _advances_offset,
    _copy_segment,
    _index_at_visible_offset,
    _insert_visible,
    _replace_visible_range,
    _rpr_at,
    _split_visible_offset,
    _visible_len,
    _visible_text,
    paragraph_to_inline_segments,
    rebuild_paragraph_from_inline,
)
from .docx_inventory import (
    DocumentSurface,
    DocxInventory,
    InventoryCoverage,
    PackagePart,
    SurfaceCapability,
    SurfaceKind,
    SurfaceVisibility,
)
from .docx_mutations import (
    SurfaceDisposition,
    SurfaceDispositionStatus,
    SurfaceMutationError,
    SurfaceMutationResult,
    SurfaceReplacement,
    apply_surface_replacements,
)
from .docx_package import (
    PackageEntry,
    PackageError,
    normalize_docx_timestamps,
    parse_package_xml,
    read_package_entries,
    restore_semantically_unchanged_xml_parts,
    write_package_atomically,
)
from .loader import document_to_bytes, load_document
from .pdf import PdfDocument, PdfExtractionMode
from .text import PlainTextDocument

__all__ = [
    "__version__",
    "DOCX_MIME",
    "MD_MIME",
    "PDF_MIME",
    "TXT_MIME",
    "DocumentBytes",
    "DocumentError",
    "DocumentKind",
    "DetectedDocumentType",
    "AddressableComment",
    "AddressableSpan",
    "DocumentSurface",
    "DocxDocument",
    "DocxInventory",
    "InventoryCoverage",
    "PackageEntry",
    "PackageError",
    "PackagePart",
    "SurfaceCapability",
    "SurfaceDisposition",
    "SurfaceDispositionStatus",
    "SurfaceKind",
    "SurfaceMutationError",
    "SurfaceMutationResult",
    "SurfaceReplacement",
    "SurfaceVisibility",
    "InlineSegment",
    "InlineSegmentKind",
    "PdfExtractionMode",
    "PdfDocument",
    "PlainTextDocument",
    "SegmentReplacement",
    "SpanRole",
    "TextSegment",
    "UnsupportedRevisionError",
    "_advances_offset",
    "_copy_segment",
    "_index_at_visible_offset",
    "_insert_visible",
    "_replace_visible_range",
    "_rpr_at",
    "_split_visible_offset",
    "_visible_len",
    "_visible_text",
    "paragraph_to_inline_segments",
    "rebuild_paragraph_from_inline",
    "apply_surface_replacements",
    "detect_document_type",
    "document_to_bytes",
    "load_document",
    "normalize_docx_timestamps",
    "parse_package_xml",
    "read_package_entries",
    "restore_semantically_unchanged_xml_parts",
    "write_package_atomically",
]
