__version__ = "0.4.3"

from .common import (
    DOCX_MIME,
    MD_MIME,
    PDF_MIME,
    TXT_MIME,
    DocumentBytes,
    DocumentError,
    DocumentKind,
)
from .detection import DetectedDocumentType, detect_document_type
from .docx import (
    AddressableComment,
    AddressableSpan,
    DocxDocument,
    InlineSegment,
    InlineSegmentKind,
    SegmentReplacement,
    SpanRole,
    TextSegment,
    UnsupportedRevisionError,
    _advances_offset,
    _copy_segment,
    _index_at_visible_offset,
    _insert_visible,
    _replace_visible_range,
    _rpr_at,
    _split_visible_offset,
    _visible_len,
    _visible_text,
    paragraph_to_inline_segments,
    rebuild_paragraph_from_inline,
)
from .loader import document_to_bytes, load_document
from .pdf import PdfDocument, PdfExtractionMode
from .text import PlainTextDocument

__all__ = [
    "__version__",
    "DOCX_MIME",
    "MD_MIME",
    "PDF_MIME",
    "TXT_MIME",
    "DocumentBytes",
    "DocumentError",
    "DocumentKind",
    "DetectedDocumentType",
    "AddressableComment",
    "AddressableSpan",
    "DocxDocument",
    "InlineSegment",
    "InlineSegmentKind",
    "PdfExtractionMode",
    "PdfDocument",
    "PlainTextDocument",
    "SegmentReplacement",
    "SpanRole",
    "TextSegment",
    "UnsupportedRevisionError",
    "_advances_offset",
    "_copy_segment",
    "_index_at_visible_offset",
    "_insert_visible",
    "_replace_visible_range",
    "_rpr_at",
    "_split_visible_offset",
    "_visible_len",
    "_visible_text",
    "paragraph_to_inline_segments",
    "rebuild_paragraph_from_inline",
    "detect_document_type",
    "document_to_bytes",
    "load_document",
]
